# Generated by Django 4.1.7 on 2023-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_post_image_delete_imagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='follower', to='App.userprofile'),
        ),
    ]
