# Generated by Django 4.1.7 on 2023-03-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
