# Generated by Django 4.1.7 on 2023-03-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_userprofile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
    ]
