# Generated by Django 4.1.7 on 2023-03-30 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_post_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='follows',
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='App.userprofile')),
                ('userprofile_following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='App.userprofile')),
            ],
        ),
    ]
