# Generated by Django 4.1.7 on 2023-03-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_remove_userprofile_follows_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers_list', to='App.userprofile'),
        ),
    ]
