# Generated by Django 4.1.7 on 2023-03-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_userprofile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
