# Generated by Django 4.1.7 on 2023-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_userprofile_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
