# Generated by Django 4.1.7 on 2023-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_description',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
