# Generated by Django 4.1.7 on 2023-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_userprofile_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
