# Generated by Django 4.1.7 on 2023-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_userprofile_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='user_white.png', upload_to=''),
        ),
    ]
